/** @type {import('jest').Config} */
const config = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/test', '<rootDir>/src'],
  testMatch: ['**/*.test.ts'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  moduleNameMapper: {
    '^(\\.{1,2}/.*)\\.js$': '$1',
  },
  transform: {
    '^.+\\.ts$': ['ts-jest', {
      tsconfig: {
        module: 'CommonJS',
        moduleResolution: 'node',
        esModuleInterop: true,
      },
    }],
    // chalk v5+ is ESM-only; Babel transform allows Jest to import it in CJS mode
    '^.+\\.m?js$': ['babel-jest', { presets: [['@babel/preset-env', { targets: { node: 'current' } }]] }],
  },
  // Allow transformation of ESM-only node_modules (chalk, ansi-styles, etc.)
  transformIgnorePatterns: [
    '/node_modules/(?!(chalk|#ansi-styles|ansi-styles|supports-color)/)',
  ],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/**/*.test.ts',
    '!src/cli/**',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  // Global thresholds raised after the integration-test hardening pass (lines/functions/statements 90%,
  // branches 78%). Per-file floors below pin modules with genuinely hard-to-reach paths (network,
  // subprocess wrappers, defensive branches) just under their current actual so regressions still fail.
  coverageThreshold: {
    global: {
      branches:   78,
      functions:  90,
      lines:      90,
      statements: 90,
    },
    './src/analyzers/AstAnalyzer.ts': { branches: 72 },
    './src/analyzers/CorrelationAnalyzer.ts': { branches: 69 },
    './src/features/capabilityMapping.ts': { lines: 89, branches: 76 },
    './src/features/customRules.ts': { lines: 87, branches: 76, functions: 87 },
    './src/features/dependencyRisk.ts': { lines: 79, branches: 74, functions: 76 },
    './src/features/entropyAnalysis.ts': { lines: 88, branches: 64 },
    './src/features/gitHooks.ts': { lines: 89 },
    './src/features/ignoreComments.ts': { branches: 75 },
    './src/features/interactiveTui.ts': { functions: 85 },
    './src/features/llm/analysis.ts': { lines: 89, branches: 71, functions: 38 },
    './src/features/llm/cache.ts': { lines: 89 },
    './src/features/llm/parser.ts': { branches: 67 },
    './src/features/llm/prompts.ts': { functions: 85 },
    './src/features/llm/providers.ts': { functions: 81 },
    './src/features/runtimeMonitor.ts': { lines: 30, branches: 24, functions: 26 },
    './src/features/scanDiff.ts': { branches: 64, functions: 85 },
    './src/features/webhooks.ts': { functions: 86 },
    './src/index.ts': { functions: 86 },
    './src/intelligence/IndicatorMatcher.ts': { branches: 74 },
    './src/intelligence/ThreatFeed.ts': { branches: 75 },
    './src/marketplace/MarketplaceScanner.ts': { lines: 87 },
    './src/mitre/atlasCatalog.ts': { branches: 72, functions: 78 },
    './src/remediation/Fixer.ts': { lines: 84, branches: 67 },
    './src/remediation/Quarantine.ts': { lines: 86, branches: 53 },
    './src/reporters/AtlasNavigatorReporter.ts': { branches: 72 },
    './src/reporters/ConsoleReporter.ts': { functions: 81 },
    './src/reporters/html/css.ts': { branches: 63 },
    './src/reporters/SarifReporter.ts': { lines: 89 },
    './src/rules/index.ts': { functions: 50 },
    './src/scanner/analyzers/SemanticAnalyzer.ts': { lines: 83, branches: 63 },
    './src/scanner/FileDiscovery.ts': { lines: 82, branches: 72 },
    './src/scanner/PatternMatcher.ts': { branches: 73 },
    './src/scanner/Scanner.ts': { lines: 86, branches: 69, functions: 86 },
    './src/scanner/WatchMode.ts': { branches: 62 },
    './src/utils/glob.ts': { lines: 85 },
    './src/utils/ignore.ts': { branches: 68 },
    './src/utils/pathSecurity.ts': { branches: 72 },
    './src/utils/redaction.ts': { branches: 75 },
    './src/utils/schemas.ts': { functions: 81 },
  },
  verbose: true,
  testTimeout: 10000,
};

export default config;
